# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator
class SafechainAgent < Formula
  desc "Safechain agent daemon"
  homepage "https://github.com/aikido/sc-agent"
  version "pr-1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AikidoSec/sc-agent/releases/download/vpr-1/sc-agent-pr-1-darwin-amd64.tar.gz"
      sha256 "48fc81f91f1d1ed6a08e3821672670f4a1a150e03f29a3a8e8e0fe8544496255"
    end
    if Hardware::CPU.arm?
      url "https://github.com/AikidoSec/sc-agent/releases/download/vpr-1/sc-agent-pr-1-darwin-arm64.tar.gz"
      sha256 "5d816a708306047129a6821ade74927c16beea56d25b8c6843f6dca743c5ceea"
    end
  end

  def install
    bin.install "sc-agent"
  end

  def post_install
    # Create plist file for launchd
    plist_path = "#{ENV['HOME']}/Library/LaunchAgents/homebrew.mxcl.sc-agent.plist"
    system "mkdir", "-p", File.dirname(plist_path)
    
    File.write(plist_path, plist_content)
    ohai "Created LaunchAgent plist at #{plist_path}"
    ohai "To start the daemon, run: launchctl load #{plist_path}"
    ohai "To stop the daemon, run: launchctl unload #{plist_path}"
  end

  def plist_content
    <<~PLIST
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>Label</key>
        <string>homebrew.mxcl.sc-agent</string>
        <key>ProgramArguments</key>
        <array>
          <string>#{bin}/sc-agent</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>StandardOutPath</key>
        <string>#{var}/log/sc-agent.log</string>
        <key>StandardErrorPath</key>
        <string>#{var}/log/sc-agent.error.log</string>
      </dict>
      </plist>
    PLIST
  end

  test do
    system "#{bin}/sc-agent", "--version"
  end
end

