// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BlockedEvent matches the daemon API response.
 */
export class BlockedEvent {
    /**
     * Creates a new BlockedEvent instance.
     * @param {Partial<BlockedEvent>} [$$source = {}] - The source object to create the BlockedEvent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("ts" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ts"] = "";
        }
        if (!("product" in $$source)) {
            /**
             * The product type (e.g., "npm", "pypi", "vscode", "chrome")
             * @member
             * @type {string}
             */
            this["product"] = "";
        }
        if (!("identifier" in $$source)) {
            /**
             * The name or identifier of the artifact
             * @member
             * @type {string}
             */
            this["identifier"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional version
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (!("bypass_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["bypass_enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlockedEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BlockedEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlockedEvent(/** @type {Partial<BlockedEvent>} */($$parsedSource));
    }
}
