// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Artifact {
    /**
     * Creates a new Artifact instance.
     * @param {Partial<Artifact>} [$$source = {}] - The source object to create the Artifact.
     */
    constructor($$source = {}) {
        if (!("product" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["product"] = "";
        }
        if (!("identifier" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["identifier"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artifact instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Artifact}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Artifact(/** @type {Partial<Artifact>} */($$parsedSource));
    }
}

/**
 * BlockEvent represents a blocked request notification from the proxy.
 */
export class BlockEvent {
    /**
     * Creates a new BlockEvent instance.
     * @param {Partial<BlockEvent>} [$$source = {}] - The source object to create the BlockEvent.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (!("ts_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ts_ms"] = 0;
        }
        if (!("artifact" in $$source)) {
            /**
             * @member
             * @type {Artifact}
             */
            this["artifact"] = (new Artifact());
        }
        if (!("block_reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["block_reason"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlockEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BlockEvent}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artifact" in $$parsedSource) {
            $$parsedSource["artifact"] = $$createField2_0($$parsedSource["artifact"]);
        }
        return new BlockEvent(/** @type {Partial<BlockEvent>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Artifact.createFrom;
