//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../changeme/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as daemon$0 from "../../../../../changeme/daemon/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "blocked": $$createType0,
        "focus_event": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = daemon$0.BlockedEvent.createFrom;
const $$createType1 = main$0.FocusEventPayload.createFrom;

configure();
