// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../changeme/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as daemon$0 from "../../../../../changeme/daemon/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "blocked": daemon$0.BlockedEvent;
            "focus_event": main$0.FocusEventPayload;
        }
    }
}
