# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator
class SafechainAgent < Formula
  desc "Safechain agent daemon"
  homepage "https://github.com/aikido/safechain-agent"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aikido/safechain-agent/releases/download/v0.1.0/safechain-agent-darwin-amd64"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"
    end
    if Hardware::CPU.arm?
      url "https://github.com/aikido/safechain-agent/releases/download/v0.1.0/safechain-agent-darwin-arm64"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"
    end
  end

  def install
    # The downloaded file is the binary itself
    # Homebrew downloads it to the build directory
    # Find the downloaded file (it might have the exact name or be sanitized)
    binary_name = Hardware::CPU.intel? ? "safechain-agent-darwin-amd64" : "safechain-agent-darwin-arm64"
    
    # Try to find the file - Homebrew might have renamed it
    downloaded_file = if File.exist?(binary_name)
      binary_name
    elsif (file = Dir.glob("*").find { |f| File.file?(f) && File.executable?(f) })
      file
    else
      raise "Could not find downloaded binary file"
    end
    
    bin.install downloaded_file => "safechain-agent"
    chmod 0755, bin/"safechain-agent"
  end

  def post_install
    # Create plist file for launchd
    plist_path = "#{ENV['HOME']}/Library/LaunchAgents/homebrew.mxcl.safechain-agent.plist"
    system "mkdir", "-p", File.dirname(plist_path)
    
    File.write(plist_path, plist_content)
    ohai "Created LaunchAgent plist at #{plist_path}"
    ohai "To start the daemon, run: launchctl load #{plist_path}"
    ohai "To stop the daemon, run: launchctl unload #{plist_path}"
  end

  def plist_content
    <<~PLIST
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>Label</key>
        <string>homebrew.mxcl.safechain-agent</string>
        <key>ProgramArguments</key>
        <array>
          <string>#{bin}/safechain-agent</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>StandardOutPath</key>
        <string>#{var}/log/safechain-agent.log</string>
        <key>StandardErrorPath</key>
        <string>#{var}/log/safechain-agent.error.log</string>
      </dict>
      </plist>
    PLIST
  end

  test do
    system "#{bin}/safechain-agent", "--version"
  end
end
