// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as daemon$0 from "./daemon/models.js";

/**
 * GetEvent returns GET /v1/events/:id.
 * @param {string} eventId
 * @returns {$CancellablePromise<daemon$0.BlockedEvent>}
 */
export function GetEvent(eventId) {
    return $Call.ByID(901265929, eventId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ListEvents returns GET /v1/events with the given limit (default 50).
 * @param {number} limit
 * @returns {$CancellablePromise<daemon$0.BlockedEvent[]>}
 */
export function ListEvents(limit) {
    return $Call.ByID(3355743684, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RequestAccess sends POST /v1/events/:id/request-access.
 * @param {string} eventId
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function RequestAccess(eventId, message) {
    return $Call.ByID(2623473656, eventId, message);
}

// Private type creation functions
const $$createType0 = daemon$0.BlockedEvent.createFrom;
const $$createType1 = $Create.Array($$createType0);
