// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FocusEventPayload is emitted when the user opens the dashboard from a block notification.
 */
export class FocusEventPayload {
    /**
     * Creates a new FocusEventPayload instance.
     * @param {Partial<FocusEventPayload>} [$$source = {}] - The source object to create the FocusEventPayload.
     */
    constructor($$source = {}) {
        if (!("eventId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FocusEventPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FocusEventPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FocusEventPayload(/** @type {Partial<FocusEventPayload>} */($$parsedSource));
    }
}
