use core::ffi::c_void;

use safechain_proxy_lib_nostd::windows::driver_protocol::{
    WFP_CALLOUT_SAFECHAIN_TCP_CONNECT_REDIRECT_V4, WFP_CALLOUT_SAFECHAIN_TCP_CONNECT_REDIRECT_V6,
    WFP_CALLOUT_SAFECHAIN_UDP_AUTH_CONNECT_BLOCK_V4,
    WFP_CALLOUT_SAFECHAIN_UDP_AUTH_CONNECT_BLOCK_V6, WFP_PROVIDER_SAFECHAIN_L4_PROXY, WindowsGuid,
};
use wdk_sys::NTSTATUS;

#[allow(
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    clippy::all,
    dead_code,
    improper_ctypes,
    improper_ctypes_definitions,
    unused_imports
)]
mod generated {
    #![allow(unsafe_op_in_unsafe_fn)]
    include!(concat!(env!("OUT_DIR"), "/wfp_bindings.rs"));
}

pub(crate) use generated::{
    FWP_BYTE_ARRAY16, FWPS_CALLOUT1, FWPS_CLASSIFY_OUT0, FWPS_CONNECT_REQUEST0, FWPS_FILTER1,
    FWPS_INCOMING_METADATA_VALUES0, FWPS_INCOMING_VALUES0, FwpsAcquireClassifyHandle0,
    FwpsAcquireWritableLayerDataPointer0, FwpsApplyModifiedLayerData0, FwpsCalloutRegister1,
    FwpsCalloutUnregisterByKey0, FwpsQueryConnectionRedirectState0, FwpsRedirectHandleCreate0,
    FwpsRedirectHandleDestroy0, FwpsReleaseClassifyHandle0, GUID,
};

#[cfg(test)]
pub(crate) use generated::{FWP_VALUE0, FWPS_INCOMING_VALUE0};

/// `STATUS_INVALID_PARAMETER` from `ntstatus.h`.
///
/// Used when callout registration is invoked with an invalid device object.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/using-ntstatus-values
pub(crate) const STATUS_INVALID_PARAMETER: NTSTATUS = -1_073_741_811_i32;

/// `FWPS_RIGHT_ACTION_WRITE` from `fwpsk.h`.
///
/// Indicates the callout may still write `FWPS_CLASSIFY_OUT0.actionType`.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/ns-fwpsk-fwps_classify_out0
pub(crate) const FWPS_RIGHT_ACTION_WRITE: u32 = 0x0000_0001;

/// `FWPS_METADATA_FIELD_PROCESS_ID` from `fwpsk.h`.
///
/// Indicates that `FWPS_INCOMING_METADATA_VALUES0.processId` is present.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/ns-fwpsk-fwps_incoming_metadata_values0
pub(crate) const FWPS_METADATA_FIELD_PROCESS_ID: u32 = 0x0000_0020;

/// `FWPS_LAYER_ALE_AUTH_CONNECT_V4` from `fwpsk.h`.
///
/// Layer ID for outbound IPv4 ALE auth-connect classification.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/fwp/management-filtering-layer-identifiers-
pub(crate) const FWPS_LAYER_ALE_AUTH_CONNECT_V4: u32 = 48;

/// `FWPS_LAYER_ALE_AUTH_CONNECT_V6` from `fwpsk.h`.
///
/// Layer ID for outbound IPv6 ALE auth-connect classification.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/fwp/management-filtering-layer-identifiers-
pub(crate) const FWPS_LAYER_ALE_AUTH_CONNECT_V6: u32 = 49;

/// `FWP_ACTION_PERMIT` from `fwptypes.h`.
///
/// Used after rewriting the connect request so WFP allows the redirected flow.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/api/fwptypes/ne-fwptypes-fwp_action_type
pub(crate) const FWP_ACTION_PERMIT: u32 = 0x0000_0002;

/// `FWP_ACTION_BLOCK` from `fwptypes.h`.
///
/// Used when the callout must deny the classified connect attempt.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/api/fwptypes/ne-fwptypes-fwp_action_type
pub(crate) const FWP_ACTION_BLOCK: u32 = 0x0000_1001;

/// `FWP_ACTION_CONTINUE` from `fwptypes.h`.
///
/// Used when this callout leaves the decision unchanged.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/api/fwptypes/ne-fwptypes-fwp_action_type
pub(crate) const FWP_ACTION_CONTINUE: u32 = 0x0000_0006;

/// `NonPagedPool` / `POOL_TYPE = 0` from `wdm.h`.
///
/// Redirect context buffers must be non-paged kernel memory.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ne-wdm-_pool_type
pub(crate) const NON_PAGED_POOL: u32 = 0;

/// Driver-owned pool tag for redirect context allocations made via
/// `ExAllocatePoolWithTag`.
///
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepoolwithtag
pub(crate) const SAFECHAIN_POOL_TAG: u32 = u32::from_ne_bytes(*b"4LCS");

/// IPv4 address-family value from Winsock headers.
///
/// Docs: https://learn.microsoft.com/en-us/windows/win32/winsock/address-families
pub(crate) const AF_INET: u16 = 2;

/// IPv6 address-family value from Winsock headers.
///
/// Docs: https://learn.microsoft.com/en-us/windows/win32/winsock/address-families
pub(crate) const AF_INET6: u16 = 23;

/// `FWP_UINT16` from `fwptypes.h`.
///
/// Generated by bindgen from the WDK `FWP_DATA_TYPE` enum.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/api/fwptypes/ne-fwptypes-fwp_data_type
pub(crate) const FWP_UINT16: i32 = generated::FWP_DATA_TYPE_::FWP_UINT16;

/// `FWP_UINT32` from `fwptypes.h`.
///
/// Generated by bindgen from the WDK `FWP_DATA_TYPE` enum.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/api/fwptypes/ne-fwptypes-fwp_data_type
pub(crate) const FWP_UINT32: i32 = generated::FWP_DATA_TYPE_::FWP_UINT32;

/// `FWP_BYTE_ARRAY16_TYPE` from `fwptypes.h`.
///
/// Generated by bindgen from the WDK `FWP_DATA_TYPE` enum.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/api/fwptypes/ne-fwptypes-fwp_data_type
pub(crate) const FWP_BYTE_ARRAY16_TYPE: i32 = generated::FWP_DATA_TYPE_::FWP_BYTE_ARRAY16_TYPE;

/// `FWPS_METADATA_FIELD_LOCAL_REDIRECT_TARGET_PID` from `fwpsk.h`.
///
/// Metadata field indicating the process ID of the local redirect target
/// for a connection.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/ns-fwpsk-fwps_incoming_metadata_values0
pub(crate) const FWPS_METADATA_FIELD_LOCAL_REDIRECT_TARGET_PID: u32 = 0x0008_0000;

/// `FWPS_METADATA_FIELD_ORIGINAL_DESTINATION` from `fwpsk.h`.
///
/// Metadata field that provides the original destination address and port
/// before any redirection was applied.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/ns-fwpsk-fwps_incoming_metadata_values0
pub(crate) const FWPS_METADATA_FIELD_ORIGINAL_DESTINATION: u32 = 0x0010_0000;

/// `FWPS_METADATA_FIELD_REDIRECT_RECORD_HANDLE` from `fwpsk.h`.
///
/// Metadata field containing a handle to the redirect record associated
/// with the connection. This is used to track and manage redirections.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/ns-fwpsk-fwps_incoming_metadata_values0
pub(crate) const FWPS_METADATA_FIELD_REDIRECT_RECORD_HANDLE: u32 = 0x0020_0000;

/// `FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_REMOTE_ADDRESS` from `fwpsk.h`.
///
/// Field index for the remote IPv4 address in the
/// `FWPS_LAYER_ALE_AUTH_CONNECT_V4` layer.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/api/fwpsu/ne-fwpsu-fwps_fields_ale_auth_connect_v4_
pub(crate) const FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_REMOTE_ADDRESS: usize = 6;

/// `FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_REMOTE_PORT` from `fwpsk.h`.
///
/// Field index for the remote port in the
/// `FWPS_LAYER_ALE_AUTH_CONNECT_V4` layer.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/api/fwpsu/ne-fwpsu-fwps_fields_ale_auth_connect_v4_
pub(crate) const FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_REMOTE_PORT: usize = 7;

/// `FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_REMOTE_ADDRESS` from `fwpsk.h`.
///
/// Field index for the remote IPv6 address in the
/// `FWPS_LAYER_ALE_AUTH_CONNECT_V6` layer.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/api/fwpsu/ne-fwpsu-fwps_fields_ale_auth_connect_v6_
pub(crate) const FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_REMOTE_ADDRESS: usize = 6;

/// `FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_REMOTE_PORT` from `fwpsk.h`.
///
/// Field index for the remote port in the
/// `FWPS_LAYER_ALE_AUTH_CONNECT_V6` layer.
/// Docs: https://learn.microsoft.com/en-us/windows/win32/api/fwpsu/ne-fwpsu-fwps_fields_ale_auth_connect_v6_
pub(crate) const FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_REMOTE_PORT: usize = 7;

/// `FWPS_CONNECTION_NOT_REDIRECTED` from `fwpsk.h`.
///
/// Generated by bindgen from the WDK `FWPS_CONNECTION_REDIRECT_STATE` enum.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/nf-fwpsk-fwpsqueryconnectionredirectstate0
pub(crate) const FWPS_CONNECTION_NOT_REDIRECTED: i32 =
    generated::FWPS_CONNECTION_REDIRECT_STATE_::FWPS_CONNECTION_NOT_REDIRECTED;

/// `FWPS_CONNECTION_REDIRECTED_BY_SELF` from `fwpsk.h`.
///
/// Generated by bindgen from the WDK `FWPS_CONNECTION_REDIRECT_STATE` enum.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/nf-fwpsk-fwpsqueryconnectionredirectstate0
pub(crate) const FWPS_CONNECTION_REDIRECTED_BY_SELF: i32 =
    generated::FWPS_CONNECTION_REDIRECT_STATE_::FWPS_CONNECTION_REDIRECTED_BY_SELF;

/// `FWPS_CONNECTION_REDIRECTED_BY_OTHER` from `fwpsk.h`.
///
/// Generated by bindgen from the WDK `FWPS_CONNECTION_REDIRECT_STATE` enum.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/nf-fwpsk-fwpsqueryconnectionredirectstate0
pub(crate) const FWPS_CONNECTION_REDIRECTED_BY_OTHER: i32 =
    generated::FWPS_CONNECTION_REDIRECT_STATE_::FWPS_CONNECTION_REDIRECTED_BY_OTHER;

/// `FWPS_CONNECTION_PREVIOUSLY_REDIRECTED_BY_SELF` from `fwpsk.h`.
///
/// Generated by bindgen from the WDK `FWPS_CONNECTION_REDIRECT_STATE` enum.
/// Docs: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/nf-fwpsk-fwpsqueryconnectionredirectstate0
pub(crate) const FWPS_CONNECTION_PREVIOUSLY_REDIRECTED_BY_SELF: i32 =
    generated::FWPS_CONNECTION_REDIRECT_STATE_::FWPS_CONNECTION_PREVIOUSLY_REDIRECTED_BY_SELF;

/// Provider GUID for the SafeChain L4 redirector.
pub(crate) const GUID_PROVIDER_SAFECHAIN_L4_PROXY: GUID = guid(WFP_PROVIDER_SAFECHAIN_L4_PROXY);
/// Callout GUID for outbound IPv4 TCP connect redirection.
pub(crate) const GUID_CALLOUT_SAFECHAIN_TCP_CONNECT_REDIRECT_V4: GUID =
    guid(WFP_CALLOUT_SAFECHAIN_TCP_CONNECT_REDIRECT_V4);
/// Callout GUID for outbound IPv6 TCP connect redirection.
pub(crate) const GUID_CALLOUT_SAFECHAIN_TCP_CONNECT_REDIRECT_V6: GUID =
    guid(WFP_CALLOUT_SAFECHAIN_TCP_CONNECT_REDIRECT_V6);
/// Callout GUID for outbound IPv4 UDP auth-connect blocking.
pub(crate) const GUID_CALLOUT_SAFECHAIN_UDP_AUTH_CONNECT_BLOCK_V4: GUID =
    guid(WFP_CALLOUT_SAFECHAIN_UDP_AUTH_CONNECT_BLOCK_V4);
/// Callout GUID for outbound IPv6 UDP auth-connect blocking.
pub(crate) const GUID_CALLOUT_SAFECHAIN_UDP_AUTH_CONNECT_BLOCK_V6: GUID =
    guid(WFP_CALLOUT_SAFECHAIN_UDP_AUTH_CONNECT_BLOCK_V6);

/// Helper for building `GUID` literals without expanding the entire WDK type
/// surface into this module.
pub(crate) const fn guid(parts: WindowsGuid) -> GUID {
    GUID {
        Data1: parts.data1,
        Data2: parts.data2,
        Data3: parts.data3,
        Data4: parts.data4,
    }
}

#[cfg(test)]
#[allow(non_camel_case_types)]
pub(crate) type FWP_VALUE0_0 = generated::FWP_VALUE0___bindgen_ty_1;
pub(crate) type SockAddrStorage = generated::sockaddr_storage;

#[link(name = "Fwpkclnt")]
unsafe extern "system" {}

#[link(name = "NtosKrnl")]
unsafe extern "system" {
    pub(crate) fn ExAllocatePoolWithTag(
        pool_type: u32,
        number_of_bytes: usize,
        tag: u32,
    ) -> *mut c_void;
}

#[cfg(test)]
#[path = "ffi_tests.rs"]
mod tests;
