// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DaemonService is a Wails-bound service that exposes daemon API calls to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as daemon$0 from "./daemon/models.js";

/**
 * @param {string} eventId
 * @returns {$CancellablePromise<daemon$0.BlockEvent>}
 */
export function GetEvent(eventId) {
    return $Call.ByID(901265929, eventId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<daemon$0.BlockEvent[]>}
 */
export function ListEvents(limit) {
    return $Call.ByID(3355743684, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} eventId
 * @returns {$CancellablePromise<void>}
 */
export function RequestAccess(eventId) {
    return $Call.ByID(2623473656, eventId);
}

// Private type creation functions
const $$createType0 = daemon$0.BlockEvent.createFrom;
const $$createType1 = $Create.Array($$createType0);
