name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

  build-unix:
    needs: extract-version
    uses: ./.github/workflows/build-macos-pkg.yml
    with:
      version: ${{ needs.extract-version.outputs.version }}
    secrets: inherit

  build-windows:
    needs: extract-version
    uses: ./.github/workflows/build-windows.yml
    with:
      version: ${{ needs.extract-version.outputs.version }}
    secrets: inherit

  release:
    needs: [extract-version, build-unix, build-windows]
    runs-on: open-source-releaser
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release files
        id: checksums
        run: |
          mv artifacts/endpoint-protection-darwin-amd64/endpoint-protection-darwin-amd64 .
          mv artifacts/endpoint-protection-darwin-arm64/endpoint-protection-darwin-arm64 .

          mv artifacts/safechain-l7-proxy-darwin-amd64/safechain-l7-proxy-darwin-amd64 .
          mv artifacts/safechain-l7-proxy-darwin-arm64/safechain-l7-proxy-darwin-arm64 .

          mv artifacts/safechain-l7-proxy-linux-amd64/safechain-l7-proxy-linux-amd64 .
          mv artifacts/safechain-l7-proxy-linux-arm64/safechain-l7-proxy-linux-arm64 .

          mv artifacts/safechain-l4-proxy-darwin-amd64/safechain-l4-proxy-darwin-amd64 .
          mv artifacts/safechain-l4-proxy-darwin-arm64/safechain-l4-proxy-darwin-arm64 .

          mv artifacts/safechain-l4-proxy-linux-amd64/safechain-l4-proxy-linux-amd64 .
          mv artifacts/safechain-l4-proxy-linux-arm64/safechain-l4-proxy-linux-arm64 .

          mv artifacts/EndpointProtection.msi/EndpointProtection.msi ./EndpointProtection.msi

          mv artifacts/EndpointProtection.pkg/EndpointProtection.pkg ./EndpointProtection.pkg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: |
            endpoint-protection-darwin-amd64
            endpoint-protection-darwin-arm64
            safechain-l7-proxy-darwin-amd64
            safechain-l7-proxy-darwin-arm64
            safechain-l7-proxy-linux-amd64
            safechain-l7-proxy-linux-arm64
            safechain-l4-proxy-darwin-amd64
            safechain-l4-proxy-darwin-arm64
            safechain-l4-proxy-linux-amd64
            safechain-l4-proxy-linux-arm64
            EndpointProtection.msi
            EndpointProtection.pkg

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
